#!/usr/bin/env python3
"""Turn the PCjs dump of the VT100 character generator ROM (DEC part 23-018E2) into
vt100/src/vt100_font.inc.

    python3 vt100/tools/mkfont.py [23-018E2.json5] > vt100/src/vt100_font.inc

Without an argument the dump is fetched from
https://www.pcjs.org/machines/dec/vt100/rom/23-018E2.json5

The ROM is copied byte for byte: 128 characters x 16 bytes, of which the video processor reads
10 per character (see vt100.c for how scans map to ROM rows).
"""
import re
import sys
import urllib.request

URL = "https://www.pcjs.org/machines/dec/vt100/rom/23-018E2.json5"


def main():
    if len(sys.argv) > 1:
        text = open(sys.argv[1]).read()
    else:
        text = urllib.request.urlopen(URL).read().decode()
    text = re.sub(r"//.*", "", text)
    rom = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})(?![0-9A-Fa-f])", text)]
    if len(rom) != 2048:
        sys.exit("expected 2048 bytes, got %d" % len(rom))
    out = sys.stdout
    out.write("/* DEC VT100 character generator ROM, part 23-018E2 (2 KB).\n")
    out.write(" * Generated by vt100/tools/mkfont.py from the dump published by PCjs:\n")
    out.write(" *   " + URL + "\n")
    out.write(" * The glyph data is DEC's (now HP's); it is reproduced unchanged so the terminal shows\n")
    out.write(" * exactly the dots a VT100 did. 16 bytes per character, most significant bit = leftmost dot. */\n")
    out.write("static const unsigned char vt100_rom[128][16] = {\n")
    for c in range(128):
        row = rom[c * 16:(c + 1) * 16]
        label = chr(c) if 32 < c < 127 and chr(c) not in "\\*/" else "0x%02X" % c
        out.write("  {" + ",".join("0x%02X" % v for v in row) + "}, /* " + label + " */\n")
    out.write("};\n")


main()
